<?php





namespace Reviews\Application\Reviews\Controllers\Admin;





use Reviews\Foundation\View;





class FormController


{


	public static function index() 


	{


		@View::render('admin.forms.index', array(), true);


	}


}