<?php

namespace Reviews\Application\Reviews\Controllers\Admin;

use Reviews\Foundation\View;

class SettingsController
{
	public static function index() 
	{
		@View::render('admin.settings.index', array(), true);
	}
}