<?php

use Reviews\Foundation\View;

?>

<?php View::startSection('breadcrumbs') ?>
	<a href="<?= admin_url('admin.php?page=reviews') ?>">Reviews List</a>
	&raquo;
	<span>Edit Review</span>
<?php View::endSection('breadcrumbs') ?>

<?php View::startSection('content') ?>
<form action="<?= admin_url('admin.php?page=reviews/update&id='. $review->id .'&noheader=true') ?>" method="post">
	<?php echo View::render('admin.reviews.form', compact('review')) ?>
 
	<?php $url = home_url() .'/Reviews/reviews/status?id='. $review->id .'&hash='. sha1(WH_REVIEW_KEY . $review->id . home_url()) .'&status='; ?>
	<!--<a href="<?= $url ?>">Status Edit</a> -->

	<button class="button button-primary">Save Changes</button>
</form>

<style>
	fieldset.fieldset legend {
		padding: 10px 0;
		font-weight: bold;
		font-size: 16px;
	}

	.form-col {
		margin-bottom: 5px;
	}
	.form-col label {
		display: inline-block;
		width: 250px;
		vertical-align: top;
	}
	.form-col input,
	.form-col select,
	.form-col textarea {
		width: 300px;
	}
</style>
<?php View::endSection('content') ?>

<?php echo View::make('layouts.main') ?>