<?php

	$option = get_option('reviews-reviews-settings');

?>
<div class="col testimonial-slide">

	<ul class="bxslider"> 

	<?php 	if ($reviews): ?>


		<?php 
	
		
		
		foreach ($reviews as $review): ?>



		<?php $av_stars = floor($review->rating * 2) / 2;

					$av_stars = str_replace(".","-", $av_stars);

		 ?>



		<li class="testimonial-slide-item">

			<div class="testimonial-slide-speech">

				<div class="testimonial-slide-speech-text">

				<?php /* <?= //nl2br($review->content) */ ?>

				<?php $testi_content = nl2br($review->content);

					if (strlen($testi_content) >= 180) {

						echo substr($testi_content, 0, 180). " ... ";

					}

					else {

						echo $testi_content;

					}

					?>

				</div>			

			</div>

			<span class="testimonial-slide-author">

				<strong><?= $review->authorfname."&nbsp;".$review->authorlname ?></strong>, <!--?= $review->state ?-->  <span class="testimonial-region"><?= $review->state ?></span> - <?= date('d M Y', strtotime($review->created_at)) ?><br>

				<span class="testimonial-stars testimonial-stars-<?php echo $av_stars; ?>"><span><?= $review->rating ?> Stars</span></span>

			</span>

		</li>

		<?php endforeach; ?>

	<?php endif; ?>

	</ul>

</div>
