<?php

use Reviews\Foundation\View;
use Reviews\Foundation\FlashMessage;

?>

<div class="wrap Reviews-page">

	<div class="breadcrumbs">
		<?= View::section('breadcrumbs') ?>
	</div>

	<?php
		echo FlashMessage::handle();
	?>

	<?= View::section('content') ?>
</div>